### ISSUE TITLE
ES7/ES2016 Cutover future plans

### ISSUE THREAD

**Issue by StevenACoffman** [exercism/xecmascript#189]
[V8 4.9.41.0 (Chrome 49) is now at 92% ES2015 compliance](https://kangax.github.io/compat-table/es6/). When v8 implements something, it takes typically 6 weeks for that v8 version to hit stable. Then, it will take typically 6 months for Node to release a major version which would use that version of v8 having those features without an experimental flag. At some point soon, the EcmaScript track will not need babel (currently 71% ES2015 support), and the solutions possible in the regular JavaScript track will be indistinguishable from the EcmaScript track.

Is the plan to tweak the EcmaScript track's babel settings to support ES2016(ES7) features like async/await, decorators,etc.?

**Comment by matthewmorgan** [comment]
@StevenACoffman I'm not aware of a specific plan yet.  I brought it up very generally with @kytrinyx in #130 just recently.

I think that might make sense-- have the JS track be reserved for things that are very widely supported, and have the ES track look forward.  I would be curious to see what @kytrinyx and @rchavarria think about this.

**Comment by kytrinyx** [comment]
I like the idea of using the ES track to look forward and the javascript track for things that are widely supported.

**Comment by rchavarria** [comment]
It seems to me that both tracks are quite similar. I was wondering if they could be merged or not. I wouldn't merge the JS one, because it has thousands of iterations and it has tons of users. On the other hand, I wouldn't merge the ES, because we would lose the opportunity to bring the bleeding edge features to users.

For now, I'd also keep both tracks: JS for widely supported features, ES for the newest ones.

**Comment by masters3d** [comment]
What are the advantages of keeping a cutting edge track (ECMA) and the current (JS) track?
Wouldn't the JS eventually adapt the new ECMA features and become just "JS"?  
Personally I see Typescript a little ahead of ECMA6/7 but I've been reluctant to start a new track because of the similarities with the current ECMA track. 
In the Swift track we drop support for the old version as soon as Apple makes an official release but that is actually expected as swift mantra is not be afraid to brake compatibility. I know that is not the JS or Python way. 

**What do you think of merging the ECMA into a new TypeScript track?**
* This should allow new ECMA6/7 features to be used within Typescript ( alas with added types).
* Since typescript is a superset of JS and in a way of ECMA6 then it should not be that hard to merge the current ECMA track into a new TypeScript track. (famous last words :).
* TypeScript seems to be production usable now (well, at least Angular2 uses it)


https://www.quora.com/Will-TypeScript-have-a-purpose-after-ES6-ES7-is-widely-adopted
http://www.slideshare.net/NeilGreen1/type-script-vs-coffeescript-vs-es6

**Comment by rchavarria** [comment]
I still agree with @kytrinyx: JS track for widely supported features (pre-ES2015) and ECMAScript track for more recent ones. There will be a point in the future where ES2015 and probably newer features will be widely supported by browsers. But, for now, I would keep them.

About merging ECMAScript and TypeScript... I'm not sure what new features brought by TypeScript would be useful for small exercises as we find on exercism.io. I don't know too much about TypeScript, there might be some interesting features not present in JS/ES2015 that would change how a developer solve exercises on exercism.io.

**Comment by kytrinyx** [comment]
I think that at the point where JS and ECMAScript have become the same thing, we can deprecate the ECMAScript track. It will have served its purpose.

**Comment by masters3d** [comment]
@rchavarria The main features that TypeScript brings to the table are:
Type annotations, compile-time type checking, Type inference, Type Generics, Tagged Unions,
When these are used with more strict compiler checks like --nonNull and TSLint you get a much better experience and very similar to what ECMA4 was suppose to be (Action Script3 was ECMA4 compliant).
I have a draft here of my exploration.
https://github.com/masters3d/xtypescript/tree/master/exercises/gigasecond

Currently I am looking at Jest for tests and TSLint for linting. 
Jest is mostly compatible with jasmine so most of the work was already done by the ECMA track. 
I am just making sure the TSLint settings and compiler flags will guide somebody to more stylistic Typescript. 

@kytrinyx  Do you mind creating a track for TypeScript?

**Comment by rchavarria** [comment]
Find in #10 the checklist used in the past to get this track publicly available. There, you'll find some information and references about how to create a track.

**Comment by rchavarria** [comment]
@masters3d Find in #10 the checklist used in the past to get this track publicly available. There, you'll find some information and references about how to create a track.

**Comment by masters3d** [comment]
I meant to say to say to create a repo so I can finalize the rest of the requirements.

**Comment by rchavarria** [comment]
Ok, sorry. I think we need help from @kytrinyx here :pray:

**Comment by kytrinyx** [comment]
> Do you mind creating a track for TypeScript?

Here you are, @masters3d: https://github.com/exercism/xtypescript/issues/1 (@vivekimsit asked for it a week ago over in https://github.com/exercism/exercism.io/issues/3369

**Comment by kytrinyx** [comment]
Oh, also: yesterday I put together a new repo for track requests https://github.com/exercism/request-new-language-track

**Comment by tejasbubane** [comment]
I think this can be closed since we now use the `babel-preset-env` which supports cutting-edge ecmascript. I don't have triage permissions on this repo, can you close this off @matthewmorgan ?

**Comment by matthewmorgan** [comment]
@tejasbubane I agree.  `env` by default supports anything defined as `latest`.  I don't think we should go as far as supporting `stage-x` features, which are experimental and subject to change.

@StevenACoffman @rchavarria please feel free to re-open this if you have concerns or objections.

**Comment by rchavarria** [comment]
I'm ok with this, thanks. I don't think we need to suppport `stage-x` features.
