### ISSUE TITLE
Missing test script in package.json

### ISSUE THREAD

**Issue by andreasolund** [exercism/xecmascript#205]
I noticed that all excercises are missing an npm test script in their package.json. Probably a suffiecient solution is to add: `"test": "gulp test"` in the script block in the master [package.json](https://github.com/exercism/xecmascript/blob/master/package.json) and re-run the _makefile_ that replaces each exercises package.json. 

Note that this was previously discussed in [Pull Request #13](https://github.com/exercism/xecmascript/pull/13/files)

**Comment by rchavarria** [comment]
Yeah, I didn't notice that.

Tests are thought to be run with `gulp test` or `gulp lint test` commands instead of `npm test`. But, there is no a big difference of using one or another. I would be happy to hear some reasons on why we should have it (please, sorry for my poor English vocabulary if this sounds too rude).

@matthewmorgan Any thought about this? I don't mind to have a `test` script on `package.json` files, but I don't see it as necessary.

**Comment by matthewmorgan** [comment]
@rchavarria I have no strong feelings either for or against it.  It would not be a big deal to change it.

@andreasolund I think your suggestion would work-- maybe you would like to create a PR for this change?

**Comment by rchavarria** [comment]
I see it as a common practice for node projects, so it's ok for me too.

**Comment by andreasolund** [comment]
Sure, I can try to make a PR for it tonight. I agree with @rchavarria that the script should be: `"test": "gulp lint test"` to get the desired result. I think it would be great to provide a widely accepted solution that makes the experience feel familiar between languages, like the exercism exercises in Go where you use `go test`!

**Comment by matthewmorgan** [comment]
Closed by #206.  Thanks @rchavarria and @andreasolund !
