### ISSUE TITLE
Babel presets? ES2016?

### ISSUE THREAD

**Issue by tejasbubane** [exercism/xecmascript#259]
I was wondering today if we should support `es2016`. More so because I feel this track should remain on the edge of ecmascript, since that is what makes it different from the javascript track.

So I looked up what preset we were using but could not find any in `gulpfile.js` (nor the `babel-preset-2016` package listed in `package.json`). Should we use a preset or was it intentional to not use one?

More importantly, should we start supporting future ES2016/ES7 features like `Array.prototype.includes()`, `decorators`, `mixins`, etc?. ref: https://developer.mozilla.org/en-US/docs/Web/JavaScript/New_in_JavaScript/ECMAScript_Next_support_in_Mozilla

**Comment by rchavarria** [comment]
Yep, the idea of this track is to support the newest features of JavaScript, while xjavascript will support wide spread JS features.

Maybe, there is no reference to `babel-preset-2016` in `package.json` because this track uses a sort of old version of Babel. So, a first step would be to update the track to the newest version of Babel. What do you think @exercism/javascript maintainers?

On the other side, I think `Array.prototype.includes()` could be interesting for the track, but other features might not be useful for the kind of exercises that are proposed in Exercism.io. Anyway, I agree on supporting newest JS features in this track.

**Comment by matthewmorgan** [comment]
@tejasbubane @rchavarria The PR that updated us to Node 7 and Babel 6 (using the `env` preset) addresses this concern I believe.  Please let me know if not, otherwise I'm going to close this ticket.

**Comment by tejasbubane** [comment]
Right. I guess this can be closes then.
