### ISSUE TITLE
Robot Name Test case there can be many robots

### ISSUE THREAD

**Issue by masters3d** [exercism/xecmascript#263]
https://github.com/exercism/xecmascript/blob/master/exercises/robot-name/robot-name.spec.js#L28

This test is assuming global state of `usedNames`. In JS5 this this the way it is because var is global. I don't think that should be the case for ES6+. I think part of it is that the class name is Robot instead of RobotName. Something like usedName or similar should be encapsulated inside the class to avoid global state.

related:
https://github.com/exercism/xjavascript/issues/105
https://github.com/exercism/xjavascript/blob/master/exercises/robot-name/robot-name.spec.js#L35

**Comment by rchavarria** [comment]
I'm not sure if I understand you. That test has nothing to do with global state. That test checks if the class `Robot` creates a new and different name each time a new instance is created.

As it was discussed on exercism/xjavascript#105, one way to check more or less this, is to create a big number of instances and check that there are no repeated names. So, the test creates `10000` instances of `Robot`, and it adds them to a `Set` (that takes care automatically of duplicated values). If the set has a length of `10000`, each `Robot` instance generated a different name. If the length is less than `10000`, there were a repeated name.

Sorry, but I don't see any global variable here. `usedNames` is a variable outside of the `for` loop, where generated robot names are added, but it's not a global one.

For me, the test provides great value to the exercise, because it forces you to use some kind of randomness in your implementation to generate robot names. Maybe, we should hear other @exercism/javascript members.

**Comment by masters3d** [comment]
My understanding is that usedNames being outside of the class will keep its state even was the Robot instance is destroyed?
https://github.com/exercism/xecmascript/blob/master/exercises/robot-name/example.js#L3

**Comment by matthewmorgan** [comment]
@masters3d @rchavarria I think you are each referring to two _different_ `usedNames` variables.  In the `robot-name` module, `usedNames` is created when the module is imported to the test suite.  It's not global per se, but more like a class-level variable (EG Java `static`.)  This is intentional, so that when new robot instances are created within the suite, we still know if the name was used previously by any other instance.

@rchavarria refers to `usedNames` _within_ the test suite, which is not global, and he correctly describes its use there.

@masters3d do you have a suggestion for a better way to generate random, non-sequential names from the `Robot` class?  You'd be welcome to make a pull request!

**Comment by masters3d** [comment]
@matthewmorgan The reset test already makes sure that the names are random and non-sequencial. The different robots names test only checks there is some kind of "global" state after an instance is destroyed. 
![image](https://cloud.githubusercontent.com/assets/6539412/23726625/c4bb66a0-0409-11e7-8a58-12bbc1c0feae.png)

Personally I don't think requiring a class variable or global variable adds anything to this exercise. If anything it adds [confusion](https://github.com/exercism/xjavascript/issues/105#issue-103624901) and to some it is an [antipattern](http://softwareengineering.stackexchange.com/questions/148108/why-is-global-state-so-evil)

The issue is that we are creating Robots when the object we should be creating is a RobotNameGenerator.

**Comment by rchavarria** [comment]
Sorry @masters3d, I thought you were talking about `usedNames` in the spec file. My fault. @matthewmorgan stated very well.

I don't think *different robot names* checks there is something global. But it's true that `Robot` implementation uses a static/global/module-level variable to be sure it generates different robot names each time a new instance is created or `reset` is called. Any improvement on this will be welcome, for sure.

Now, looking at the tests about `reset` and *different robot names*, they look almost the same, and they probably test the same piece of code in `Robot` implementation, but each one demonstrate a different spec to accomplish. So I see both tests useful.

About `RobotNameGenerator`, it can be thought as a helper class, used by `Robot`, to get names. But it doesn't need to be tested separately. It can be tested through `Robot` (both constructor and `reset` method).

Any idea about how to avoid that variable at scope level?

**Comment by masters3d** [comment]
Perhaps encapsulating the global state implicitly into an object like `RobotNameGenerator` that is then explicitly required by a `Robot`  in order to initialize it. 

```JS
class RobotNameGenerator {
  usedNames = {}
  //other state or methods
}

class Robot {
// require a name generator instance to initialize.
}

//usage

  xit('there can be lots of robots with different names each', () => {
    const NUMBER_OF_ROBOTS = 10000;
    const usedNames = new Set();
    const generator = new RobotNameGenerator(); // added

    for (let i = 0; i < NUMBER_OF_ROBOTS; i++) {
      const newRobot = new Robot(generator); // changed
      usedNames.add(newRobot.name);
    }

    expect(usedNames.size).toEqual(NUMBER_OF_ROBOTS);
  });
```
In the case above the Robot class is only holding the name which is not too useful. The exercise is about generating robot names not robots themselves.  Alternatively, You can just create a RobotName class that only generates names. 
https://github.com/masters3d/xtypescript/blob/master/exercises/robot-name/robot-name.test.ts

**Comment by rchavarria** [comment]
I understand the idea of `RobotNameGenerator` to generate robot names and to store generated names, to avoid repetition. It's nice.

But, I'm not sure about passing it through the constructor of `Robot` (or `RobotName`). This `RobotNameGenerator` depends on how we (track maintainers) solve the problem. But that doesn't necessarily needs to be how Exercism users will solve the problem. Forcing them to pass a generator to `Robot` will force them to use a similar solution to the one in the track.

And, it will force them to implement the solution in two different files, but when you submit a solution, you usually submit just one file (I don't know if users can submit several files).

What do you think @matthewmorgan ?

**Comment by masters3d** [comment]
I am not proposing that solution per se. I think the best solution is to get rid of it thus the PR. 
Just feel free to close it if you are not in accordance. 

I guess the next step would be to make the canonical data not introduce JS's shenanigans. :) I just don't have time for that right now.

**Comment by matthewmorgan** [comment]
@rchavarria @masters3d I think there's semantic value in creating a class that manages the generation of robot names.  It is a bit more sophisticated approach and I agree that it would require the submission of two classes, or functions would serve also in JavaScript.

I don't think deleting the test is the way to go.  Making some attempt to test for randomness is worthwhile, if for no other reason than to provoke thought and discussion about how difficult the problem of testing for randomness is.

@masters3d you've indicated that you don't have enough time to explore this further  Thanks for bringing it up, and if you do find time to work on it, we would welcome further discussion.

**Comment by masters3d** [comment]
> Making some attempt to test for randomness is worthwhile, if for no other reason than to provoke thought and discussion about how difficult the problem of testing for randomness is.

We are not on the same page. As I indicated [here](https://github.com/exercism/xecmascript/issues/263#issuecomment-285196899),  randomness is being tested twice. The `different robots` test doesn't add anything that the `reset test` doesn't already catch as far as randomness goes. The tests are identical except for one tracking global state.  

The implicit global state is what is confusing because `different robots` **requires** global state. 
@matthewmorgan How does requiring global state add to the randomness in this problem?

**Comment by matthewmorgan** [comment]
@masters3d the reset test is not intended to test randomness, but simply that:
1. Resetting the name name of a given Robot instance
2. Ensuring that the new name does not equal the previous one.

In fact, the reset test is not even _remotely_ sufficient to make sure the names generated are random--  it only tests two names.  Even testing 10,000 names, as the current test for randomness does, is not sufficient to guarantee the algorithm that the user has chosen is generating random names, underscoring my point about how difficult it is to ensure randomness, a point that is well worth discussing in the exercise, but really isn't currently.

What you refer to as "global" state is not "global" at all.  It's a variable that exists during the life of the module in to which it is imported (the test suite) and keeps track of all the names ever generated by Robot instances during those tests.  It is not available to other modules that are imported into the same test suite, but only to instances of Robot.  It is shared among instances of the class or prototype-- as I said earlier, like a `private`, class-level `static` in Java.

My earlier comments probably missed the mark on the next point: The `usedNames` variable is not in fact required for the generation of _random_ names, but for the generation of _unique_ names.  We must have some mechanism for keeping track of generated names _within_ the Robot class that is independent of the number or lifespan of Robot instances.  Without that mechanism, name generation could be perfectly random, and even non-sequential, but wouldn't be guaranteed to be unique.  Uniqueness is one of the requirements of the exercise, to cite the `README`: 

> Your solution should not allow the use of the same name twice when avoidable.

I assert that avoiding the use of the same name is entirely avoidable in the implementation of a solution, and that's what `usedNames` facilitates.  We are of course open to other ways to make it happen.

If I confused this discussion by asserting that `usedNames` and its implementation were for _random_ name generation rather than _unique_ name generation I apologize for the lack of specificity.

**Comment by masters3d** [comment]
What about adding a hint file describing the requirement to never repeat a name? 

https://github.com/exercism/x-common/pull/728#issuecomment-287468275

**Comment by matthewmorgan** [comment]
@masters3d there is currently a requirement to that effect in the `description.md` file, are you suggesting we put it in a hint file as well? 

If we were to do that, I would think that some language that makes it clear that in ES it is possible to ensure unique name generation, and that the tests look for that would be appropriate.

Does it seem like we're repeating ourselves if we do this, or clarifying something that is currently too vague?

**Comment by rchavarria** [comment]
I didn't know hints could be added to single exercises.

I don't like to provide too many hints, so that exercises remain as open as possible. That helps generating discussions in the platform. But I don't see a big issue about adding them (some users will read them, some users don't).

It feels a bit of duplication, but, as I see it, it could be done this way: the gerenal `README` file states that no name should be repeated; the `HINT` file provides some tips about how to achieve that: module level variable,... (more or less what @masters3d pulled on https://github.com/exercism/x-common/pull/728).

**Comment by masters3d** [comment]
"In some exercism language tracks there are tests to ensure that the same name is never used twice."
Thats not a requirement. Thats opt in.

**Comment by kotp** [comment]
And given the limitation, it is not possible eventually, as we run out of space... it is a discussion point that comes up on the site occasionally, depending on how they are doing on exploration.

**Comment by matthewmorgan** [comment]
@rchavarria it sounds as if we need to make a decision as to whether we think that the presence of the "same name is never used twice" language in the description is enough, or if we need to add a `HINT.md` file.  Personally I have no strong feelings about it either way.  

I would _not_ want us to use the adjective "global" to describe a potential solution, as global values should be discouraged as a matter of conveying best practices.  And, with due respect to @masters3d , I stand by my assertion that including a module or "class private" level variable is not the same as introducing a global variable.  I do agree with @masters3d that _if_ we were using global values, that would be bad, but we're not.

**Comment by kotp** [comment]
@rchavarria said:
> I don't know if users can submit several files from [this comment](https://github.com/exercism/xecmascript/issues/263#issuecomment-286571999)

I just wanted to answer "yes" to that doubt.  It is possible.  [Here is an example](http://exercism.io/submissions/cc99bc1839ab403d9afc7790b14c5652) of doing such a thing.

**Comment by matthewmorgan** [comment]
@kotp thanks for your help!

**Comment by rchavarria** [comment]
> In some exercism language tracks there are tests to ensure that the same name is never used twice

Ok, it's not a requirement, it's optional, but this track has opted for it. Sorry, I don't remember when, or who, but the test is there, and I'd like to keep it. I think it provides some value to the exercise.

But, I think adding a hint is a good idea. The hint could say that this track has chosen to ensure that the same name is *never* used twice, so the user needs to implement something to obey that: module level variables, external generator,...

@masters3d What do you think about that? Would you like to add that hint file?

**Comment by masters3d** [comment]
Would you prefer a comment or a hint file? 
https://github.com/exercism/xocaml/blob/master/exercises/robot-name/test.ml#L37

```
Optionally: make this test pass.
There are 26 * 26 * 10 * 10 * 10 = 676,000 possible Robot names.
This test generates all possible Robot names, and checks that there are
no duplicates. It's harder to make pass than the other tests, so it is left
as optional.
To enable it, uncomment the code in the run_test_tt_main
line at the bottom of this module.
```

**Comment by rchavarria** [comment]
Whoa! The comment idea is very interesting. Ok, nobody takes comments seriously, but it's interesting :stuck_out_tongue_closed_eyes: 

What about both? hint and comment. In fact, they could be very similar.

**Comment by kotp** [comment]
I think since the practitioner is going to edit the tests, they are likely to comment out the skips as they are used to doing, they are going to be in that file, when their tests fail, and that test doesn't look like the others, they are likely to read the comments.  Or at least more likely, at that point.

People are funny though, sometimes they can't see the ketchup in the door for the ketchup on the second shelf of the fridge.
