### ISSUE TITLE
ReferenceError: regeneratorRuntime babel-present-env error?

### ISSUE THREAD

**Issue by arthurchipdean** [exercism/xecmascript#295]
I think this may be a bug with `babel-preset-env`, just checking here first. I'm getting the error below when trying to run the tests for a new exercise I'm implementing. This error refers to this line: `function* generate(A) {`. Generator functions are part of the `babel-preset-es2015` which should be included in `babel-preset-env` so I'm not sure why this is happening. Any ideas? Thanks!

```
 ● Test suite failed to run

    ReferenceError: regeneratorRuntime is not defined

      at Object.<anonymous> (exercises/alphametics/tmp/alphametics.js:57:15)
      at Object.<anonymous> (exercises/alphametics/tmp/temp.alphametics.spec.js:1:122)

Test Suites: 1 failed, 1 total

```

**Comment by rchavarria** [comment]
I have no idea :(

@exercism/javascript ?

**Comment by matthewmorgan** [comment]
@arthurchipdean @rchavarria I will try to investigate this later.  I think the first step is to see if I can reproduce it.  Personally, I haven't tried using generators under our current setup.

**Comment by rchavarria** [comment]
I have no idea about how to configure Babel nowadays (I did it in the past, but it has evolved a lot since then).

But just looking at the documentation, if I compare the support for [arrow functions](https://babeljs.io/docs/plugins/transform-es2015-arrow-functions) (a basic feature that makes sense to be included by default) to [generators](https://babeljs.io/docs/plugins/transform-regenerator) (a not so basic feature) I notice a difference:

The generators documentation shows a *warning*:

> Runtime required
> You need to use either the Babel polyfill or the regenerator runtime so that regeneratorRuntime will be defined.

It seems if we want to use generators we need a plugin.

**Comment by arthurchipdean** [comment]
@rchavarria You are right, after adding the babel-polyfil the error has gone away. Thanks for your help!

**Comment by tejasbubane** [comment]
@arthurchipdean Can you check if this works? https://babeljs.io/docs/plugins/transform-regenerator/#usage-via-babelrc-recommended-

Since [babel-plugin-transform-regenerator](https://github.com/exercism/xecmascript/blob/master/yarn.lock#L533) is already installed, I think it would be better if that can be used instead of adding a new package.

**Comment by arthurchipdean** [comment]
@tejasbubane  Yes that worked! I removed the babel-polyfil dependency and added the .babelrc file.
