### ISSUE TITLE
Should test for Grains use BigInt instead of String?

### ISSUE THREAD

**Issue by matthewmorgan** [exercism/xecmascript#56]
@rchavarria this test imports BigInt but doesn't use it, instead requiring the student return results as strings.  It looks like the JS track was edited to make the same change.

It seems like in both cases ```grains.spec.js``` should use BigInt or remove the import.  

What would you like to do?

**Comment by rchavarria** [comment]
You're right. `grains.spec.js` shouldn't import `BigInt`. The solution should. Can you remove that line from `grains.spec.js`, please? I think I forgot to clean it up, sorry.

Tests expect a `String` representation because some tested values don't fit into a JavaScript number, but `BigInt` is hidden to tests (that's why they shouldn't import it). Returning a `String` looks fine to me.

**Comment by matthewmorgan** [comment]
I pushed this change for the Ecmascript repo, but for some reason I was not able to get the commit message to accurately reflect the change I made.  It seems to be showing something older from my local history. 

If you have any tips on correcting this, I would appreciate it.

**Comment by kytrinyx** [comment]
Try pushing `git push -f origin your-branch-name`

**Comment by matthewmorgan** [comment]
Got it.  Thanks @kytrinyx , getting a better understanding of git for sure!

**Comment by kytrinyx** [comment]
One of my favorite resources if you have a couple of hours free is https://www.youtube.com/watch?v=1ffBJ4sVUb4 (Git for Ages 4 and Up)

**Comment by matthewmorgan** [comment]
closed by PR#59
