### ISSUE TITLE
Add new test to Gigasecond problem

### ISSUE THREAD

**Issue by rchavarria** [exercism/xecmascript#57]
[exercism/xjavascript PR#125](https://github.com/exercism/xjavascript/pull/125) adds a new test to the problem. It would be nice to add a similar one to this repository.

**Comment by matthewmorgan** [comment]
@rchavarria I was looking at this and there's another important difference between the JS track and the ES track: the JS track expects an answer rounded down to midnight of the resulting giga-birthday, and the ES track does not round down.  

I prepared a new test in the current style of the ES track for the ES track, but I'm wondering if the tracks should agree better.  Does it matter?

**Comment by kytrinyx** [comment]
Check out the shared metadata for gigasecond: https://github.com/exercism/x-common/blob/master/gigasecond.json

**Comment by matthewmorgan** [comment]
@kytrinyx if I understand that metadata spec correctly, then the JS track test is not correct bc it drops the minutes and seconds from the ```expectedDate```.  It uses midnight as the starting point rather than some arbitrary time of day, but 1GS later can (so should) include the minutes and seconds.

So, the ES track is right and the JS track needs fixing.

Do I have it right?

**Comment by kytrinyx** [comment]
Agreed, the JS track should handle arbitrary times of day.

**Comment by matthewmorgan** [comment]
OK submitted a fix as [exercism/xjavascript PR#129](https://github.com/exercism/xjavascript/pull/129)

**Comment by kytrinyx** [comment]
Cool, I'll close this issue, then.
